server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: go-app
  static_configs:
  - targets:
      - localhost:8080
    labels:
      job: go-app
  pipeline_stages:
  - match:
      selector: '{job="go-app"}'
      stages:
      - regex:
          expression: "(?P<log>.+)"