- name: Build Lavarel application
  hosts: db
  become: true
  become_user: root
  roles:
    - role: db

- name: Build Lavarel application
  hosts: server
  become: true
  become_user: root
  roles:
    - role: server
